FROM amazonlinux:latest

# install required os packages
RUN yum -y update
RUN yum -y install zip gzip tar java-11-amazon-corretto git which procps-ng jq

# download, build, and install python3
RUN yum -y install gcc-c++ make openssl-devel bzip2-devel libffi-devel sqlite-devel
RUN mkdir -p /opt/src
WORKDIR /opt/src
RUN curl https://www.python.org/ftp/python/3.9.13/Python-3.9.13.tgz > Python-3.9.13.tgz
RUN tar -xzf Python-3.9.13.tgz
WORKDIR Python-3.9.13
RUN ./configure --enable-optimizations --with-openssl=/usr --enable-loadable-sqlite-extensions
RUN make -j 4 install

# install the local dynamodb service
RUN mkdir -p /opt/dynamodb
WORKDIR /opt/dynamodb
RUN curl https://s3.us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz > dynamodb_local_latest.tar.gz
RUN tar -xzf dynamodb_local_latest.tar.gz

# install required python packages
RUN pip3 install awscli coverage pytest pylint boto3 bcrypt PyJWT

# configure the AWS CLI with a junk account
# Note: Profile name must match what is found in python/src/wrfcloud/resources/env_vars.yaml -> codebuild.AWS_PROFILE
RUN mkdir -p ~/.aws && touch ~/.aws/credentials && chmod -R go-rwx ~/.aws
RUN echo "[junk]" >> ~/.aws/credentials
RUN echo "aws_access_key_id = XXXXXXXXXXXXXXXXXXXX" >> ~/.aws/credentials
RUN echo "aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >> ~/.aws/credentials
RUN echo "region = us-east-1" >> ~/.aws/credentials
RUN echo "output = json" >> ~/.aws/credentials

# install nodejs and angular cli
RUN curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -
RUN yum -y install nodejs
RUN npm install -g @angular/cli

# start the local dynamodb service when the container starts
#CMD java -jar /opt/dynamodb/DynamoDBLocal.jar -inMemory &
