FROM amazonlinux:latest

# install required os packages
RUN yum -y update
RUN yum -y install zip gzip tar java-11-amazon-corretto git which procps-ng jq wget

# download, build, and install python3
RUN yum -y install gcc-c++ make openssl-devel bzip2-devel libffi-devel sqlite-devel zlib-devel
RUN mkdir -p /opt/src
WORKDIR /opt/src
RUN curl https://www.python.org/ftp/python/3.9.13/Python-3.9.13.tgz > Python-3.9.13.tgz
RUN tar -xzf Python-3.9.13.tgz
WORKDIR Python-3.9.13
RUN ./configure --enable-optimizations --with-openssl=/usr --enable-loadable-sqlite-extensions
RUN make -j 4 install

# install the local dynamodb service
RUN mkdir -p /opt/dynamodb
WORKDIR /opt/dynamodb
RUN curl https://s3.us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz > dynamodb_local_latest.tar.gz
RUN tar -xzf dynamodb_local_latest.tar.gz

# install required python packages
RUN pip3 install awscli coverage pytest pylint boto3 bcrypt PyJWT

# configure the AWS CLI with a junk account
# Note: Profile name must match what is found in python/src/wrfcloud/resources/env_vars.yaml -> codebuild.AWS_PROFILE
RUN mkdir -p ~/.aws && touch ~/.aws/credentials && chmod -R go-rwx ~/.aws
RUN echo "[junk]" >> ~/.aws/credentials
RUN echo "aws_access_key_id = XXXXXXXXXXXXXXXXXXXX" >> ~/.aws/credentials
RUN echo "aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >> ~/.aws/credentials
RUN echo "region = us-east-1" >> ~/.aws/credentials
RUN echo "output = json" >> ~/.aws/credentials

# install nodejs and angular cli
RUN touch "${HOME}/.bashrc"
RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
RUN source ~/.nvm/nvm.sh; nvm install 16
RUN source ~/.bashrc; npm install -g @angular/cli@14
RUN echo -n 'ewogICIkc2NoZW1hIjogIi4vbm9kZV9tb2R1bGVzL0Bhbmd1bGFyL2NsaS9saWIvY29uZmlnL3NjaGVtYS5qc29uIiwKICAidmVyc2lvbiI6IDEsCiAgImNsaSI6IHsKICAgICJjb21wbGV0aW9uIjogewogICAgICAicHJvbXB0ZWQiOiB0cnVlCiAgICB9LAogICAgImFuYWx5dGljcyI6ICJhY2UxOTcxNS01Y2Q5LTQyYTItODI2Mi1jYmVlNDFhOTNjNWMiCiAgfSwKICAicHJvamVjdHMiOiB7fQp9Cg==' | base64 -d > ~/.angular-config.json
RUN echo -n 'CiMgTG9hZCBBbmd1bGFyIENMSSBhdXRvY29tcGxldGlvbi4Kc291cmNlIDwobmcgY29tcGxldGlvbiBzY3JpcHQpCg==' | base64 -d >> ~/.bashrc
RUN source ~/.bashrc

