---
Description: WRF Cloud API Data
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  AppName:
    Description: Application name (alphanumeric and underscores only)
    Type: String
    AllowedPattern: '[A-Za-z0-9_]+'
  DeploymentType:
    Description: May be PRODUCTION or DEVELOPMENT
    Type: String
    Default: development
    AllowedValues:
      - production
      - development
  WrfCloudBucket:
    Description: Name of S3 bucket used by the entire application
    Type: String

Conditions:
  IsDev: !Equals [ !Ref DeploymentType, 'development' ]
  IsProd: !Equals [ !Ref DeploymentType, 'production' ]

Resources:

  AuditTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${DeploymentType}_${AppName}_audit'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: ref_id
          AttributeType: S
      KeySchema:
        - AttributeName: ref_id
          KeyType: HASH

  RefreshTokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${DeploymentType}_${AppName}_refresh_tokens'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: refresh_token
          AttributeType: S
      KeySchema:
        - AttributeName: refresh_token
          KeyType: HASH

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${DeploymentType}_${AppName}_users'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH

  JobTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${DeploymentType}_${AppName}_jobs'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH

  SubscriberTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${DeploymentType}_${AppName}_subscribers'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: client_url
          AttributeType: S
      KeySchema:
        - AttributeName: client_url
          KeyType: HASH

  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${WrfCloudBucket}'



Outputs:
  AuditTable:
    Description: DynamoDB Table - Audit
    Value: !GetAtt AuditTable.Arn
    Export:
      Name: !Sub 'dynamodb-table-audit-${DeploymentType}-${AppName}'
  RefreshTokenTable:
    Description: DynamoDB Table - Refresh Tokens
    Value: !GetAtt RefreshTokenTable.Arn
    Export:
      Name: !Sub 'dynamodb-table-refresh-tokens-${DeploymentType}-${AppName}'
  UserTable:
    Description: DynamoDB Table - Users
    Value: !GetAtt UserTable.Arn
    Export:
      Name: !Sub 'dynamodb-table-users-${DeploymentType}-${AppName}'
  JobTable:
    Description: DynamoDB Table - Jobs
    Value: !GetAtt JobTable.Arn
    Export:
      Name: !Sub 'dynamodb-table-jobs-${DeploymentType}-${AppName}'
  SubscriberTable:
    Description: DynamoDB Table - Subscribers
    Value: !GetAtt SubscriberTable.Arn
    Export:
      Name: !Sub 'dynamodb-table-subscribers-${DeploymentType}-${AppName}'
  WrfCloudBucket:
    Description: S3 Bucket used to store WRF Cloud data
    Value: !Ref DataBucket
    Export:
      Name: 'wrfcloud-s3-bucket'
  WrfCloudBucketRegionalDomainName:
    Description: Regional Domain Name for the S3 Bucket
    Value: !GetAtt DataBucket.RegionalDomainName
    Export:
      Name: 'wrfcloud-s3-bucket-regional-domain-name'
