name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'
    steps:
    - uses: checkout@v3
      with:
        fetch-depth: ‘2’
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Run code coverage script
      run: |
        pip install coverage
        python/coverage.sh
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
