name: Code Coverage

on: [push, pull_request]

jobs:
  Codecov:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Run code coverage script
      run: |
        pip install coverage
        pwd
        ls ./python/coverage.sh
        cat ./python/coverage.sh
        ./python/coverage.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./python/test/coverage.xml
        verbose: true
